---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Rome"
  COREDNS_ADDR: "10.43.0.10"
  KUBE_API_ADDR: "10.17.1.199"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"
  NODE_CIDR: "10.17.1.0/24"
