apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZF5ViRO6rJ8=,iv:Sl+z4wgQD4G2HrXO3KK8PF6W+6LlxFkkusLXl5CTk5c=,tag:bIdY5CJ7rzeP/v/9Yy8J7g==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:9Ec6eCi6Nrv4Iyfl8ZwW069brcySXQ==,iv:QLFMA7Z7L6+mWX5BQO4tN/1IrSS951BmzATtGxIBL40=,tag:LO0KIX+X1l9zpGlGSDH7Qg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:s+UXwMku724wo2/bFT55WZdpasuYKB/L51HjRPvvo8Ci9RRB,iv:6LlIlmPg/MqYrVQqvp9qbXM/BshR+odnO/7aKr+Cx0Q=,tag:g9Rvzy2HI4hHwP4tzlJFog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdFRlNGZ2UU9iU1NQR3ZX
            VGQwazk0YXdrTHFYQVhjS20zb3ZJRGM0OVU0Ckxrb2FraTByQTAzV1NlTzFoZUEx
            RlNaSnZ4dUhRdHlGM0ltbGxuaXJqZzAKLS0tIGpiUDJ1ZStxT0F5Z2dzNzYrQ0d0
            ME5tTG40KytmTGt1dmxnWXlmYTJJWVEKqMpFc9IdpFtELfSA0FbpjtiQdPGDFk7L
            AHZIiDtUtCVrntSMKKcbIKGl40OJSlz0OA1IEO+7H0HQF/9UK7n92w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T23:48:49Z"
    mac: ENC[AES256_GCM,data:8GF+9lSQlmkUkuapCtQ+kxmqD3vfEOo2Chn8pK9Ymy5Cfln/s5ZdK7fwRRpeURFjkIdF9oR2uLGH+JEhZYscFMFqR2ZEeVjj5IvVRkgAYRl3vZ5//Ec+V/Ev5tH7Fizdq4HDTDso5F7nUvszYsg8vVS00osJS1DQMRYPmkRU6J8=,iv:soY507Z9z4uhJLTbPzVGPV7MtANEP0hgbmcbjXAF9Ck=,tag:S+CzzIY2+/WhEzCbOT+IiQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
