apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Zr2kf6IZe9czeWg2popItRQ9s8s1yOVyVDljfSEa0+/smnsFmR07tA==,iv:gtreVUrQUUQb4J17FACN+PIEY2dU2UOdo3aYoTJJo2Y=,tag:4vD4s40jqTGbVaWx8N090w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19ufzusf8ls394p4kl5498myl24w7x6ggc5w9grq4tk8dcyh709ls6ku97r
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5QytQSytKbFdZY1c0a0NN
            V083dHNUNDVMZEw5dERBS3YvdnFjRlZSN1NFCjVXbGN0dDIwT3p3N084TytSV0Fa
            ejlLSUVBVUpnZjhGbjgxQjNhRjJHK3cKLS0tIFNvQ1hnNDlCdDIzVkNLMXJJWFcr
            WWJTQjhvWm1hS0o0K25laHBzR2xjMG8KG7FdDIiuiqjRoyR+U9LpNpEGVGY0Cvj2
            LylXCc+j2pPNpCs6n/Q5y/PNujeIR+kGjyg7XQKZSPqMr3ggzkCiMA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-19T23:48:48Z"
    mac: ENC[AES256_GCM,data:4H9lyXf4wYs2XM2z7km2R3rpsrjfRr0vZ2XzY1ZpZ+PV4yl+X0OYgiiw089Nz75xHxQzWfELQin0Q75rQJl/prfbxgsN30PjxuAn1kM3sC2Nz+UemUvetiLq6zwv3qYqHb2x28TNv5+8gQRmvrOe7XJME6jveUN8Ww5jVC4YlAE=,iv:Z7EVhcwSp3OXUdUViYnaNgwgR8UQhmitst0VpjDqhOw=,tag:A+t9u86lS5a8CT3v7/WGyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
